#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : ISLP Solutions  
author                      : Mohamed Badry  
copyright                   : "2025"  
logo                        : images/logo.svg 

# Disable execution on each build
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/Mohamed-Badry/islp-solutions
  branch: main  

html:
  favicon: "images/book.png"
  use_issues_button: true
  use_repository_button: true
  navigation_depth: -1
  analytics:
    google_analytics_id: "G-ECXWDYFXFV"

# Add launch buttons to each page
launch_buttons:
  notebook_interface: "jupyterlab"  
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"


parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath
    - deflist
    - html_admonition
    - html_image
    - linkify
    - tasklist
  
