#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : ISLP Solutions  
author                      : Mohamed Badry  
copyright                   : "2025"  
logo                        : logo.svg 

# Disable execution on each build
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/Mohamed-Badry/islp-exercises  # Online location of your book
  # path_to_book:   # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)


html:
  use_issues_button: true
  use_repository_button: true
  
  # check if these are hallucinations
  use_edit_page_button: false
  navigation_depth: 2

# Add launch buttons to each page
launch_buttons:
  colab_url: "https://colab.research.google.com"


parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath
    - deflist
    - html_admonition
    - html_image
    - linkify
    - tasklist
  
